---
kind: pipeline
type: docker
name: linux-amd64
platform:
  arch: amd64
  os: linux
steps:
- name: test
  image: golang:1.14.4
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
  - go build
  - go test
  
- name: frontend
  image: node
  commands:
  - npm install
  - npm test

