kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: Drone-Testin-Dev/drone-test1
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
